menubar: true
height: 300
toolbar:
  - undo redo | formatselect | bold italic backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | image | help
plugins:
  - image
  # - imagetools
  - quickbars
  - advlist
  - autolink
  - lists
  - link
  - charmap
  # - print
  - preview
  - anchor
  - searchreplace
  - visualblocks
  - code
  - fullscreen
  - insertdatetime
  - media
  - table
  # - paste
  - help
  - wordcount
quickbars_image_toolbar: alignleft aligncenter alignright
images_upload_url: "/tinymce_assets"
relative_urls : false
license_key: 'gpl'
